artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_indigestion
  source_url: https://github.com/prashant-022/Datasets/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_indigestion/data.zip
  unzip_dir: artifacts/data_indigestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5